"""
Generate May_12 offline package folders for client and server bundles.

Default output:
    May_12/client/offline-packages
    May_12/server/offline-packages

Examples:
    python tools/offline_package_generator.py --target all
    python tools/offline_package_generator.py --target client --source X:\\prepared-offline-packages
    python tools/offline_package_generator.py --target server --python-installer installers/python-3.13.5-amd64.exe
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path


TARGETS = ("client", "server")
DEFAULT_PYTHON_VERSION = "3.13"
DEFAULT_PLATFORM = "win_amd64"
DEFAULT_IMPLEMENTATION = "cp"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def may12_root() -> Path:
    return repo_root() / "May_12"


def selected_targets(target: str) -> list[str]:
    if target == "all":
        return list(TARGETS)
    return [target]


def remove_existing_package(package_dir: Path) -> None:
    for name in ("wheelhouse", "ffmpeg", "installers"):
        path = package_dir / name
        if path.exists():
            shutil.rmtree(path)
    for name in ("manifest.sha256", "README.md"):
        path = package_dir / name
        if path.exists():
            path.unlink()


def copy_tree_if_present(source: Path, destination: Path) -> bool:
    if not source.exists():
        return False
    if source.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        return True
    shutil.copytree(source, destination, dirs_exist_ok=True)
    return True


def copy_existing_source(source: Path, package_dir: Path) -> None:
    wheelhouse = source / "wheelhouse"
    if not wheelhouse.is_dir() or not any(wheelhouse.glob("*.whl")):
        raise SystemExit(f"Existing source has no wheelhouse with wheels: {wheelhouse}")
    copy_tree_if_present(wheelhouse, package_dir / "wheelhouse")
    copy_tree_if_present(source / "ffmpeg", package_dir / "ffmpeg")
    copy_tree_if_present(source / "installers", package_dir / "installers")


def download_wheels(
    requirements: Path,
    destination: Path,
    *,
    python_version: str,
    platform: str,
    implementation: str,
) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    major_minor = python_version.replace(".", "")
    command = [
        sys.executable,
        "-m",
        "pip",
        "download",
        "--only-binary=:all:",
        "--platform",
        platform,
        "--implementation",
        implementation,
        "--python-version",
        python_version,
        "--abi",
        f"cp{major_minor}",
        "--abi",
        "abi3",
        "--abi",
        "none",
        "--dest",
        str(destination),
        "-r",
        str(requirements),
    ]
    print("RUN " + " ".join(command))
    subprocess.run(command, check=True)


def copy_ffmpeg_from_path(package_dir: Path) -> None:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        print("WARNING: ffmpeg was not found in PATH; offline package will not include ffmpeg.")
        return
    source_bin = Path(ffmpeg).resolve().parent
    copy_tree_if_present(source_bin, package_dir / "ffmpeg" / "bin")


def copy_python_installer(installer: str, package_dir: Path) -> None:
    if not installer:
        return
    source = Path(installer).expanduser().resolve()
    if not source.is_file():
        raise SystemExit(f"Python installer not found: {source}")
    copy_tree_if_present(source, package_dir / "installers" / source.name)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_manifest(package_dir: Path) -> None:
    entries: list[str] = []
    for path in sorted(package_dir.rglob("*")):
        if not path.is_file() or path.name == "manifest.sha256":
            continue
        relative = path.relative_to(package_dir).as_posix()
        entries.append(f"{sha256(path)} *{relative}")
    (package_dir / "manifest.sha256").write_text("\n".join(entries) + "\n", encoding="ascii")


def write_readme(package_dir: Path, target: str) -> None:
    text = f"""# May_12 {target.title()} Offline Packages

This folder is generated by `tools/offline_package_generator.py`.

Use from the `{target}` bundle folder:

```bat
python setup.py --offline
```

Contents:
- `wheelhouse/` - Python wheels used with `pip --no-index`.
- `ffmpeg/bin/` - optional FFmpeg binaries.
- `installers/` - optional manual-use installers.
- `manifest.sha256` - SHA-256 hashes for package files.
"""
    (package_dir / "README.md").write_text(text, encoding="utf-8")


def generate_for_target(target: str, args: argparse.Namespace) -> None:
    bundle_dir = may12_root() / target
    requirements = bundle_dir / "requirements.txt"
    if not requirements.is_file():
        raise SystemExit(f"Requirements file not found: {requirements}")

    package_dir = bundle_dir / "offline-packages"
    package_dir.mkdir(parents=True, exist_ok=True)
    remove_existing_package(package_dir)

    if args.source:
        copy_existing_source(Path(args.source).expanduser().resolve(), package_dir)
    else:
        download_wheels(
            requirements,
            package_dir / "wheelhouse",
            python_version=args.python_version,
            platform=args.platform,
            implementation=args.implementation,
        )
        copy_ffmpeg_from_path(package_dir)

    copy_python_installer(args.python_installer, package_dir)
    write_readme(package_dir, target)
    write_manifest(package_dir)
    print(f"Generated {target} offline package: {package_dir}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate May_12 offline dependency packages.")
    parser.add_argument("--target", choices=("all", "client", "server"), default="all")
    parser.add_argument("--source", default="", help="Copy wheelhouse/ffmpeg/installers from an existing offline source instead of downloading wheels.")
    parser.add_argument("--python-installer", default="", help="Optional Python installer to copy into offline-packages/installers.")
    parser.add_argument("--python-version", default=DEFAULT_PYTHON_VERSION, help="Python version for wheel download, default 3.13.")
    parser.add_argument("--platform", default=DEFAULT_PLATFORM, help="pip download platform, default win_amd64.")
    parser.add_argument("--implementation", default=DEFAULT_IMPLEMENTATION, help="pip download implementation, default cp.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    for target in selected_targets(args.target):
        generate_for_target(target, args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
